# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DDPlayerProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DDPlayerProject

  pod 'Masonry'

  target 'DDPlayerProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DDPlayerProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
